# Exploratory Data Analysis - Capstone Project

## Imports and Data Load

In [207]:
#For Data Manipulation
import pandas as pd
import numpy as np

#For Visualizations
import matplotlib.pyplot as plt
import seaborn as sns

#For Displays
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option("display.width", None)

#Plot Styling
sns.set_style('whitegrid')

In [208]:
# Load cleaned roster dataset
clean_rosters_df = pd.read_csv("../data/processed/rosters_clean.csv")

clean_rosters_df.head()

,jersey_number,player_name,position,class_year,high_school,previous_school,school_name,division,conference_code,primary_conference,source_url,collected_at,height_inches,hometown_city,hometown_state,hometown_country,season
0,1.0,Becca Siedenburg,S,SR,Kettle Moraine HS,Gardner-Webb,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,68.0,Wales,WI,USA,2025
1,2.0,Avery Thaler,MB,SO,Fairfield HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,70.0,Fairfield,TX,USA,2025
2,4.0,Rachel Koss,S,JR,Freedom HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,71.0,Freedom,WI,USA,2025
3,5.0,Courtney Church,OH,R-FR,Veritas Academy,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,72.0,Driftwood,TX,USA,2025
4,7.0,Hannah Gonzalez,MB,JR,Lovejoy HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,74.0,Lucas,TX,USA,2025

## Data Inspection

In [209]:
# Dataset Dimensions
# This will tell us how many rows and columns are in the dataframe. This is recorded as
# (rows, columns).
clean_rosters_df.shape

(2123, 17)

In [210]:
# Column Names and Data Types
# This will tell us all of the column names in the dataframe, as well as what type of data
# is stored in each column.
clean_rosters_df.info()
# You can see there is mostly string types in this set, meaning free text.
# There is also a few integer types or float, which are numeric values.
# As this is mostly string data, our cleaning process was VERY important to get our data
# to be usable and correct for analysis.

<class 'pandas.DataFrame'>
RangeIndex: 2123 entries, 0 to 2122
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   jersey_number       2103 non-null   float64
 1   player_name         2123 non-null   str
 2   position            2091 non-null   str
 3   class_year          1966 non-null   str
 4   high_school         1609 non-null   str
 5   previous_school     206 non-null    str
 6   school_name         2123 non-null   str
 7   division            2123 non-null   str
 8   conference_code     2123 non-null   str
 9   primary_conference  2123 non-null   str
 10  source_url          2123 non-null   str
 11  collected_at        2123 non-null   str
 12  height_inches       1820 non-null   float64
 13  hometown_city       2123 non-null   str
 14  hometown_state      1883 non-null   str
 15  hometown_country    2123 non-null   str
 16  season              2123 non-null   int64
dtypes: float64(2), int64(1), str(14)
memory usage: 282.1 KB

In [211]:
# Preview of the Data
clean_rosters_df.head(10)
# This shows us the first 10 rows of the dataset. As our data is categorized by school (as
# it was how it was pulled), these players will likely be from the same university.

,jersey_number,player_name,position,class_year,high_school,previous_school,school_name,division,conference_code,primary_conference,source_url,collected_at,height_inches,hometown_city,hometown_state,hometown_country,season
0,1.0,Becca Siedenburg,S,SR,Kettle Moraine HS,Gardner-Webb,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,68.0,Wales,WI,USA,2025
1,2.0,Avery Thaler,MB,SO,Fairfield HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,70.0,Fairfield,TX,USA,2025
2,4.0,Rachel Koss,S,JR,Freedom HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,71.0,Freedom,WI,USA,2025
3,5.0,Courtney Church,OH,R-FR,Veritas Academy,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,72.0,Driftwood,TX,USA,2025
4,7.0,Hannah Gonzalez,MB,JR,Lovejoy HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,74.0,Lucas,TX,USA,2025
5,8.0,Annaleise Sevier,OH,SO,Aubrey HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,70.0,Aubrey,TX,USA,2025
6,9.0,Ashli Edmiston,OH,SR,Wilsonville HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,68.0,Wilsonville,OR,USA,2025
7,10.0,Aubrey Beaver,OH,JR,Temecula Valley HS,Cal State Fullerton,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,72.0,Murrieta,CA,USA,2025
8,11.0,Izabelle Larson,OH,JR,Santa Teresa HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,71.0,San Jose,CA,USA,2025
9,12.0,Abby Christian,L/DS,JR,Liberty North HS,NaN,Abilene Christian University,DI,WAC,Western Athletic Conference,https://acusports.com/sports/womens-volleyball...,2026-07-20T00:46:56.672717+00:00,69.0,Kansas City,MO,USA,2025

In [212]:
# Checking for Duplicates
# As there could be multiple people in the dataset with the same name (Emily Smith, for example), 
# we will check for duplicates based on the combination of first name, last name, and school. 
# This will help us identify if there are any duplicate entries in the dataset.
clean_rosters_df.duplicated(subset=["player_name", "school_name"]).sum()
# With the result of 0, we can confidently say there are no duplicate athletes in the df.

np.int64(0)

In [213]:
# Calculating Missing Values by Column
# In the informational code, we learned there are some missing data in columns. This could be 
# due to data not being available, like if someone was an international student or if someone
# did not transfer, so there's not a previous school available.
# This code calculates the precentage of missing values from each column.
# Calculate missing values by column
missing_values = pd.DataFrame({
    "missing_count": clean_rosters_df.isnull().sum(),
    "missing_percent": (clean_rosters_df.isnull().sum() / len(clean_rosters_df) * 100).round(2)
})

missing_values.sort_values("missing_percent", ascending=False)

                    missing_count  missing_percent
previous_school              1917            90.30
high_school                   514            24.21
height_inches                 303            14.27
hometown_state                240            11.30
class_year                    157             7.40
position                       32             1.51
jersey_number                  20             0.94
player_name                     0             0.00
school_name                     0             0.00
conference_code                 0             0.00
division                        0             0.00
source_url                      0             0.00
primary_conference              0             0.00
collected_at                    0             0.00
hometown_city                   0             0.00
hometown_country                0             0.00
season                          0             0.00

In [214]:
# Review unique categorical values
for column in ["position", "class_year", "division", 
               "conference_code", "hometown_country", "season"]:
    print(f"\n{column.upper()}")
    print(clean_rosters_df[column].value_counts(dropna=False))

POSITION
position
OH      652
MB      548
S       382
L/DS    345
OPP     164
NaN      32
Name: count, dtype: int64

CLASS_YEAR
class_year
FR             567
SO             410
JR             389
SR             334
NaN            157
GR              76
R-FR            56
R-SO            53
R-JR            43
R-SR            17
FY.              9
FY               4
RF.              2
5TH              2
R-JUNIOR         2
RFR.             1
R-SOPHOMORE      1
Name: count, dtype: int64

DIVISION
division
DI    2123
Name: count, dtype: int64

CONFERENCE_CODE
conference_code
MVC              141
MAAC             128
Southland        123
SWAC             111
Summit           102
WAC               96
ACC               95
CAA               92
Big Sky           89
Big East          85
Horizon           78
ASUN              74
WCC               74
CUSA              73
MEAC              71
Mountain West     61
SBC               57
A10               54
SEC               53
Big West          49
PL                48
B12               47
Mid American      46
Ohio Valley       46
American          37
Big South         36
America East      35
IVY               33
B10               33
Southern          30
NEC               26
Name: count, dtype: int64

HOMETOWN_COUNTRY
hometown_country
USA                    1850
Brazil                   32
Turkey                   31
Italy                    29
Poland                   26
PR                       19
CAN                      13
Serbia                   13
Argentina                 8
Canada                    8
Sweden                    5
Hungary                   5
Greece                    5
Germany                   5
Netherlands               5
France                    5
Bulgaria                  4
Peru                      4
Slovenia                  3
Czech Republic            3
Cyprus                    3
New Zealand               3
Costa Rica                2
Colombia                  2
Mexico                    2
Spain                     2
Romania                   2
ON                        2
Alberta                   2
Egypt                     2
Türkiye                   2
Slovakia                  2
Brasil                    2
Japan                     2
Croatia                   2
Finland                   2
Taiwan                    1
Estonia                   1
Ukraine                   1
P.R.                      1
Czechia                   1
W.Va.                     1
Latvia                    1
Calif. / Rocklin HS       1
Tex. / Mansfield HS       1
Poland`                   1
Turkiye                   1
Russia                    1
China                     1
Belarus                   1
Dominican Republic        1
Hawai’i                   1
Name: count, dtype: int64

SEASON
season
2025    2123
Name: count, dtype: int64

## Feature Engineering

In [215]:
# Copying the original dataframe so we can feature engineer and have something 
# to fall back on!
crfedf = clean_rosters_df.copy()

In [216]:
# Standardizing Records
# We're changing FY and FY. to be FR, as first years are also freshmen.
crfedf["class_year"] = crfedf["class_year"].replace({
    "FY": "FR",
    "FY.": "FR",
    "RF.": "R-FR",
    "RFR.": "R-FR",
    "5TH": "R-SR",
    "R-JUNIOR": "R-JR",
    "R-SOPHOMORE": "R-SO"
})

# Remove features not relevant to the analysis
# Jersey numbers and the high school name are not relevant to success.
# We will remove these columns as we have a city and state available for the player.
crfedf = crfedf.drop(columns=[
    "jersey_number",
    "high_school"
])

# We are verifying the shape change and acquiring information on the new df.
crfedf.shape
crfedf.info()

<class 'pandas.DataFrame'>
RangeIndex: 2123 entries, 0 to 2122
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   player_name         2123 non-null   str
 1   position            2091 non-null   str
 2   class_year          1966 non-null   str
 3   previous_school     206 non-null    str
 4   school_name         2123 non-null   str
 5   division            2123 non-null   str
 6   conference_code     2123 non-null   str
 7   primary_conference  2123 non-null   str
 8   source_url          2123 non-null   str
 9   collected_at        2123 non-null   str
 10  height_inches       1820 non-null   float64
 11  hometown_city       2123 non-null   str
 12  hometown_state      1883 non-null   str
 13  hometown_country    2123 non-null   str
 14  season              2123 non-null   int64
dtypes: float64(1), int64(1), str(13)
memory usage: 248.9 KB

## Feature Validation

In [217]:
# Review categorical variables after feature engineering
categorical_columns = [
    "position",
    "class_year",
    "division",
    "conference_code",
    "hometown_state",
    "hometown_country"
]

for column in categorical_columns:
    print(f"\n{column.upper()}")
    print(crfedf[column].value_counts(dropna=False))

POSITION
position
OH      652
MB      548
S       382
L/DS    345
OPP     164
NaN      32
Name: count, dtype: int64

CLASS_YEAR
class_year
FR      580
SO      410
JR      389
SR      334
NaN     157
GR       76
R-FR     59
R-SO     54
R-JR     45
R-SR     19
Name: count, dtype: int64

DIVISION
division
DI    2123
Name: count, dtype: int64

CONFERENCE_CODE
conference_code
MVC              141
MAAC             128
Southland        123
SWAC             111
Summit           102
WAC               96
ACC               95
CAA               92
Big Sky           89
Big East          85
Horizon           78
ASUN              74
WCC               74
CUSA              73
MEAC              71
Mountain West     61
SBC               57
A10               54
SEC               53
Big West          49
PL                48
B12               47
Mid American      46
Ohio Valley       46
American          37
Big South         36
America East      35
IVY               33
B10               33
Southern          30
NEC               26
Name: count, dtype: int64

HOMETOWN_STATE
hometown_state
TX                   325
NaN                  240
CA                   165
IL                   112
FL                    98
IN                    73
OH                    67
GA                    62
AZ                    61
NC                    60
WI                    53
MN                    53
UT                    47
MO                    41
MI                    40
VA                    36
CO                    36
NY                    35
TN                    33
IA                    33
KY                    32
PA                    32
WA                    32
MD                    30
KS                    30
LA                    29
HI                    23
NE                    22
OR                    20
NV                    19
AR                    19
NJ                    18
AL                    16
ON                    15
SC                    14
ID                    13
MA                    11
SD                    11
CT                     9
MT                     9
MS                     8
OK                     6
NM                     4
WV                     3
WY                     3
NH                     2
Wielkopolska           2
Mugla                  2
DE                     2
MB                     1
Izmir                  1
Mato Grosso            1
AB                     1
Manitoba               1
Bursa                  1
Paraná                 1
Istanbul               1
San Juan Province      1
Rio de Janeiro         1
San Juan               1
DC                     1
Santa Catarina         1
ME                     1
QC                     1
BC                     1
ND                     1
Name: count, dtype: int64

HOMETOWN_COUNTRY
hometown_country
USA                    1850
Brazil                   32
Turkey                   31
Italy                    29
Poland                   26
PR                       19
CAN                      13
Serbia                   13
Argentina                 8
Canada                    8
Sweden                    5
Hungary                   5
Greece                    5
Germany                   5
Netherlands               5
France                    5
Bulgaria                  4
Peru                      4
Slovenia                  3
Czech Republic            3
Cyprus                    3
New Zealand               3
Costa Rica                2
Colombia                  2
Mexico                    2
Spain                     2
Romania                   2
ON                        2
Alberta                   2
Egypt                     2
Türkiye                   2
Slovakia                  2
Brasil                    2
Japan                     2
Croatia                   2
Finland                   2
Taiwan                    1
Estonia                   1
Ukraine                   1
P.R.                      1
Czechia                   1
W.Va.                     1
Latvia                    1
Calif. / Rocklin HS       1
Tex. / Mansfield HS       1
Poland`                   1
Turkiye                   1
Russia                    1
China                     1
Belarus                   1
Dominican Republic        1
Hawai’i                   1
Name: count, dtype: int64

In [218]:
# Review countries represented in the dataset
crfedf["hometown_country"].value_counts(dropna=False)

hometown_country
USA                    1850
Brazil                   32
Turkey                   31
Italy                    29
Poland                   26
PR                       19
CAN                      13
Serbia                   13
Argentina                 8
Canada                    8
Sweden                    5
Hungary                   5
Greece                    5
Germany                   5
Netherlands               5
France                    5
Bulgaria                  4
Peru                      4
Slovenia                  3
Czech Republic            3
Cyprus                    3
New Zealand               3
Costa Rica                2
Colombia                  2
Mexico                    2
Spain                     2
Romania                   2
ON                        2
Alberta                   2
Egypt                     2
Türkiye                   2
Slovakia                  2
Brasil                    2
Japan                     2
Croatia                   2
Finland                   2
Taiwan                    1
Estonia                   1
Ukraine                   1
P.R.                      1
Czechia                   1
W.Va.                     1
Latvia                    1
Calif. / Rocklin HS       1
Tex. / Mansfield HS       1
Poland`                   1
Turkiye                   1
Russia                    1
China                     1
Belarus                   1
Dominican Republic        1
Hawai’i                   1
Name: count, dtype: int64

In [219]:
# Review U.S. state/province values
sorted(crfedf["hometown_state"].dropna().unique())

['AB',
 'AL',
 'AR',
 'AZ',
 'BC',
 'Bursa',
 'CA',
 'CO',
 'CT',
 'DC',
 'DE',
 'FL',
 'GA',
 'HI',
 'IA',
 'ID',
 'IL',
 'IN',
 'Istanbul',
 'Izmir',
 'KS',
 'KY',
 'LA',
 'MA',
 'MB',
 'MD',
 'ME',
 'MI',
 'MN',
 'MO',
 'MS',
 'MT',
 'Manitoba',
 'Mato Grosso',
 'Mugla',
 'NC',
 'ND',
 'NE',
 'NH',
 'NJ',
 'NM',
 'NV',
 'NY',
 'OH',
 'OK',
 'ON',
 'OR',
 'PA',
 'Paraná',
 'QC',
 'Rio de Janeiro',
 'SC',
 'SD',
 'San Juan',
 'San Juan Province',
 'Santa Catarina',
 'TN',
 'TX',
 'UT',
 'VA',
 'WA',
 'WI',
 'WV',
 'WY',
 'Wielkopolska']

In [220]:
# Reviewing Cleaned Work
# Review cleaned position categories
crfedf["position"].value_counts(dropna=False)

position
OH      652
MB      548
S       382
L/DS    345
OPP     164
NaN      32
Name: count, dtype: int64

In [221]:
# Review cleaned class-year categories
crfedf["class_year"].value_counts(dropna=False)

class_year
FR      580
SO      410
JR      389
SR      334
NaN     157
GR       76
R-FR     59
R-SO     54
R-JR     45
R-SR     19
Name: count, dtype: int64